; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Marauder-Mini]
board = esp32dev
board_build.partitions = custom_4Mb_full.csv
build_src_filter =${env.build_src_filter} +<../boards/marauder-mini>
build_flags =
	${env.build_flags}
	-Iboards/marauder-mini
	-Os
	-DCORE_DEBUG_LEVEL=0
	-DCONFIG_ESP32_JTAG_SUPPORT_DISABLE=1
	-D MARAUDER_MINI
	-DUSER_SETUP_LOADED=1
; SERIAL (GPS) dedicated pins
	-DSERIAL_TX=1
	-DSERIAL_RX=3

	;Buttons configuration
	-DHAS_BTN =1
    -DSEL_BTN= 34
	-DUP_BTN= 36
	-DDW_BTN= 35
	-DR_BTN= 39
	-DL_BTN =26
	-DHAS_5_BUTTONS
	-DBTN_ALIAS= "\"Ok\""
	-DBTN_ACT = LOW

	;-DALLOW_ALL_GPIO_FOR_IR_RF=1 ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	;Infrared Led default pin and state
	-DRXLED= 16
	-DLED=17
	-DLED_ON= HIGH
	-DLED_OFF= LOW

		;CC1101 SPI connection pins
	; best connection pins for higher speed https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/spi_master.html#gpio-matrix-and-io-mux
	-DUSE_CC1101_VIA_SPI
	-DCC1101_GDO0_PIN=15
	-DCC1101_SS_PIN=27
	-DCC1101_MOSI_PIN=SPI_MOSI_PIN
	-DCC1101_SCK_PIN=SPI_SCK_PIN
	-DCC1101_MISO_PIN=SPI_MISO_PIN
	-DCC1101_GDO2_PIN=22  

	; connections are the same as CC1101
	-DUSE_NRF24_VIA_SPI
	-DNRF24_CE_PIN=15
	-DNRF24_SS_PIN=27  ; chip select
	-DNRF24_MOSI_PIN=SPI_MOSI_PIN
	-DNRF24_SCK_PIN=SPI_SCK_PIN
	-DNRF24_MISO_PIN=SPI_MISO_PIN

	
	;Font sizes, depending on device
	-DFP=2
	-DFM=2
	-DFG=2

	;Screen Setup
	-DHAS_SCREEN=1
	-DROTATION=1
	-DMINBRIGHT=160

	;TFT_eSPI Setup
	-DUSER_SETUP_LOADED=1
	-DST7789_DRIVER=1
	-DUSE_HSPI_PORT=1
	-DTFT_HEIGHT=240
	-DTFT_WIDTH=240
	-DTFT_MISO=-1
	-DTFT_SDA=13
	-DTFT_SCL=14
	-DTFT_CS=-1
	-DTFT_DC=2
	-DTFT_RST=4
	-DTFT_BL= -1
	-DTFT_BACKLIGHT_ON=HIGH
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY = 27000000
	-DSPI_READ_FREQUENCY=16000000
	-DSPI_TOUCH_FREQUENCY=2500000

	;TouchScreen Controller
	-DHAS_TOUCH=-1

	;SD Card Setup pins
	-DSDCARD_CS=5
	-DSDCARD_SCK=18
	-DSDCARD_MISO=19
	-DSDCARD_MOSI=23

	;Default I2C port
	-DGROVE_SDA=33
	-DGROVE_SCL=25

	-DSPI_SCK_PIN=18
	-DSPI_MOSI_PIN=23
	-DSPI_MISO_PIN=19
	-DSPI_SS_PIN=1 ;grove beside SDCard
	
	-DDEVICE_NAME='"Marauder mini"'

lib_deps =
	${env.lib_deps}
	 fastled/FastLED @3.9.4

[env:Awok-Mini]
extends = env:Marauder-Mini
board_build.partitions = custom_16Mb.csv
board_upload.maximum_size = 16777216
board_upload.flash_size=16MB

[env:Marauder-v7]
board = esp32dev
board_build.partitions = custom_4Mb_full.csv
build_src_filter =${env.build_src_filter} +<../boards/marauder-mini>
build_flags =
	${env.build_flags}
	-Iboards/marauder-mini
	-Os
	-DCORE_DEBUG_LEVEL=0
	-DCONFIG_ESP32_JTAG_SUPPORT_DISABLE=1
	-D MARAUDER_MINI
	-DUSER_SETUP_LOADED=1
	-DILI9341_DRIVER=1
	-DUSE_HSPI_PORT=1
	-DTFT_HEIGHT=320
	-DTFT_WIDTH=240
	-DTFT_MISO=19
	-DTFT_MOSI=23
	-DTFT_SCLK=18
	-DTFT_CS=17
	-DTFT_DC=26
	-DTFT_RST=-1
	-DTFT_BL=32
	-DTFT_BACKLIGHT_ON=HIGH
	-DSMOOTH_FONT=1
	-DTOUCH_CS=-1
	-DSPI_FREQUENCY=27000000
	-DDEVICE_NAME='"Marauder v7"'

lib_deps =
	${env.lib_deps}


[env:LAUNCHER_Marauder-Mini]
extends=env:Marauder-Mini
board_build.partitions = custom_4Mb.csv
build_flags =
	${env:Marauder-Mini.build_flags}
	-DCORE_DEBUG_LEVEL=0
	-DCONFIG_ESP32_JTAG_SUPPORT_DISABLE=1
	-DLITE_VERSION=1
	-DDEVICE_NAME='"Launcher Marauder mini"'

[env:LAUNCHER_Marauder-v7]
extends=env:Marauder-v7
board_build.partitions = custom_4Mb.csv
build_flags =
	${env:Marauder-v7.build_flags}
	-DCORE_DEBUG_LEVEL=0
	-DCONFIG_ESP32_JTAG_SUPPORT_DISABLE=1
	-DLITE_VERSION=1
	-DDEVICE_NAME='"Launcher Marauder v7"'
